homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('tambah/', views.tambah, name='tambah'),
    # path('profile/', views.profile, name='profile'),
    # dilanjutkan ...
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story9/', include('story9.urls')),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
]

homepage/models.py
from django.db import models
# Create your models here.

class Aktivitas(models.Model):
    kegiatan = models.CharField('Aktivitas', max_length=120, null=True)
    # bisa string kosong
    deskripsi = models.TextField('Deskripsi', blank=True) 
    tanggal = models.DateField('Tanggal', null=True)

    def __str__(self):
        return self.kegiatan


class Tamu(models.Model):
    # menguhubungkan kelas tamu dengan kelas aktivitas sebagai superclassnya 
    kegiatan = models.ForeignKey(Aktivitas, on_delete=models.CASCADE, null=True)
    nama = models.CharField('Name', max_length=120, null=True)

    def __str__(self):
        return self.nama

story7/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django.forms import ModelForm
from .models import Aktivitas, Tamu


class BukuTamuForm(ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Aktivitas
        fields = '__all__'

class PartisipanForm(ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Tamu
        fields = '__all__'

# class ParticipantForm(ModelForm):
#     required_css_class = 'required'

#     class Meta:
#         model = Participant
#         fields = '__all__'

homepage/views.py
from django.shortcuts import render
from .models import Aktivitas, Tamu
from .forms import BukuTamuForm, PartisipanForm
from django.http import HttpResponseRedirect
# Create your views here.

def index(request):
    submit = False
    list_aktivitas = Aktivitas.objects.all()
    list_tamu = Tamu.objects.all()
    if request.method == 'POST':
        form = PartisipanForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/?submit=True')
    else:
        form = PartisipanForm()
        if 'submit' in request.GET:
            submit = True
    return render(request, 'index.html', {'form': form, 'submit': submit, 'list_aktivitas': list_aktivitas, 'list_tamu': list_tamu})

def tambah(request):
    submit = False
    if request.method == 'POST':
        form = BukuTamuForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/tambah/?submit=True')
    else:
        form = BukuTamuForm()
        if 'submit' in request.GET:
            submit = True
    return render(request, 'tambah.html', {'form': form, 'submit': submit})

story7/views.py
from django.shortcuts import render

# Create your views here.

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages

# Create your views here.


def log_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if User.objects.filter(username=username).exists():
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/story9/login/')
            else:
                messages.error(request, 'Password doesn\'t match')
        else:
            messages.error(request, 'Username doesn\'t exist')
    return render(request, 'login.html')


def home(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        if User.objects.filter(username=username).exists():
            messages.error(request, 'Username is already taken')
        elif User.objects.filter(email=email).exists():
            messages.error(request, 'Email is already taken')
        else:
            user = User.objects.create_user(username, email, password)
            return redirect('/story9/login/')
    return render(request, 'index2.html')


def log_out(request):
    logout(request)
    return redirect('/story9/')

homepage/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bootstrap-4.5.2-dist\css\bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="{% static 'bootstrap-4.5.2-dist\js\bootstrap.js' %}"></script>
    <title>story6</title>
</head>
{% include "navbar.html" %}
<div class="container-fluid col-12 pt-5">
    <section class="container-fluid flex-wrap align-content-center mb-5">

    <h1>Open Class</h1>
    <h1>Kaum Rebahan</h1>

    <div class="pt-4">
        <table class="table-hover table table-borderless mx-5 mb-5 m-auto" style="width:90vw">
            <thead class="text-center" style="color: aliceblue;">
                <tr>
                <th>Aktivitas</th>
                <th>Waktu</th>
                <th>Deskripsi</th>
                <th>Partisipan</th>
                </tr>
            </thead>
    
        <tbody>
            {% for aktivitas in list_aktivitas %}
            <tr id="spesialtr">
            <td class="text-center"><b>{{ aktivitas.kegiatan }}</b></td>
            <td class="text-center">{{ aktivitas.tanggal }}</td>
            <td class="text-center">{{ aktivitas.deskripsi }}</td>
            <td class="text-center">
                {% for partisipan in list_tamu %}
                    {% if partisipan.kegiatan == aktivitas %}
                        <div>
                            {{ partisipan }}
                        </div>
                    {% endif %}
                {% endfor %}
            </td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>
    <div class="pt-3">
        <form action="" method="POST" novalidate>
            {% csrf_token %}
            
            <table class="table mx-5 table-borderless" style="width:40vw; color:aliceblue;">
                {% if submit %}
                <tr>
                    <td>&nbsp;</td>
                    <td style="color: white;">Berhasil bergabung dengan kaum rebahan</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>
                        <button class="btn d-flex click">
                            <a href="{% url 'homepage:index' %}" class="text-dark">
                                Ikut kegiatan rebahan lainnya
                            </a>
                        </button>
                    </td>
                </tr>
                {% else %}
        
                {{ form.as_table }}
                <tr>
                    <td>&nbsp;</td>
                    <td>
                        <input type="submit" value="Submit" class="btn click" />
                    </td>
                </tr>
                {% endif %}
            </table>
            </form>
    </div>
    </section>
    </div>
</body>
</html>

homepage/templates/navbar.html
<nav class="navbar sticky-top navbar-expand-sm navbar-light" style="padding-left: 3%;">
    <a class="navbar-brand"href="{% url 'homepage:index' %}">
        <svg width="30" height="30" viewBox="0 0 62 62" fill="none" xmlns="http://www.w3.org/2000/svg">
            <g clip-path="url(#clip0)">
            <path d="M44.5261 43.4589H40.6525C40.4108 44.7399 39.2864 45.7096 37.9355 45.7096H34.8627L34.8632 45.7086C34.129 46.5946 33.0945 47.2251 31.9101 47.4422C33.3916 50.5018 36.5258 52.6119 40.153 52.6119H53.3579C53.5372 52.6119 53.6795 52.462 53.6734 52.2827C53.5003 47.3803 49.4711 43.4589 44.5261 43.4589Z" fill="#D7D7D7"/>
            <path d="M27.1373 45.7091H24.065C22.7136 45.7091 21.5892 44.7399 21.3475 43.4589H17.4739C12.5289 43.4589 8.49973 47.3798 8.32661 52.2827C8.32046 52.462 8.46284 52.6114 8.64211 52.6114H21.847C25.4746 52.6114 28.6089 50.5013 30.0899 47.4413C28.9059 47.2251 27.8719 46.5946 27.1373 45.7091Z" fill="#D7D7D7"/>
            <path d="M36.1167 42.1551C35.4341 32.2594 35.2246 29.0584 35.1432 27.9254C35.112 27.4879 35.0108 27.0587 34.8433 26.656L34.8225 26.6055C34.1887 25.0771 32.7384 24.0863 31.1339 24.0863H31.1112C29.4982 24.0863 28.0295 25.0751 27.3966 26.6138C27.3923 26.6231 27.3885 26.6325 27.3848 26.6418C27.2159 27.0489 27.1109 27.4805 27.0792 27.9229C27.0205 28.7435 26.8053 31.9121 26.6918 33.5852C26.6497 34.2076 26.3091 34.7634 25.7893 35.0778C23.1706 36.662 21.4101 39.6045 21.4101 42.9752C21.4101 44.5595 22.6484 45.8436 24.1763 45.8436H26.3299C26.8597 45.8436 27.3753 46.0388 27.7707 46.4052C28.6553 47.2253 29.8232 47.7266 31.1117 47.7266C34.0222 47.7266 36.3224 45.1662 36.1167 42.1551V42.1551Z" fill="white"/>
            <path d="M22.3026 45.2145L27.3112 45.215C30.21 45.215 32.5007 42.6543 32.2958 39.6427C31.2425 24.2997 31.3193 25.0478 31.2534 24.6485C31.1724 24.4758 31.0942 24.3017 31.0207 24.1246C31.0155 24.1113 31.0089 24.0991 31.0033 24.0863C32.5893 24.1172 34.0099 25.114 34.6383 26.6362C34.7118 26.8133 34.79 26.9874 34.871 27.1601C34.9209 27.4628 35.1993 31.5977 35.3312 33.5829C35.3727 34.2059 35.7118 34.7617 36.2295 35.0762C38.8367 36.6612 40.5899 39.6035 40.5899 42.9746C40.5899 44.5586 39.3567 45.8429 37.8353 45.8429C37.8353 45.8429 36.5922 45.8429 35.6906 45.8429C35.1626 45.8424 34.6496 46.0381 34.2558 46.4045C33.375 47.2248 32.212 47.7266 30.9293 47.7266C29.6462 47.7266 28.4832 47.2248 27.6023 46.4045C27.209 46.0386 26.6956 45.8429 26.1675 45.8429H24.0229C23.3719 45.8429 22.7737 45.6079 22.3022 45.215L22.3026 45.2145Z" fill="white"/>
            <path d="M61.0918 19.2099H58.9419C58.6203 19.2099 58.3398 18.9971 58.2475 18.6891C56.6227 13.2626 51.5855 9.44531 45.816 9.44531C39.9378 9.44531 34.8201 13.4078 33.2965 18.9975C31.7795 18.6617 30.2205 18.6617 28.7035 18.9975C27.1799 13.4078 22.0622 9.44531 16.184 9.44531C10.4145 9.44531 5.37732 13.2626 3.75249 18.6891C3.66025 18.9971 3.37975 19.2099 3.05809 19.2099H0.908203C0.406799 19.2099 0 19.6167 0 20.1181V24.7272C0 25.2291 0.406799 25.6355 0.908203 25.6355H3.05809C3.37975 25.6355 3.66072 25.8483 3.75249 26.1562C5.37732 31.5828 10.4145 35.4001 16.184 35.4001C21.3759 35.4001 26.0569 32.3178 28.1089 27.5479C28.6089 26.3861 29.7437 25.6355 31 25.6355C32.2563 25.6355 33.3911 26.3861 33.8911 27.5474C35.9431 32.3178 40.6241 35.4001 45.816 35.4001C51.5855 35.4001 56.6227 31.5828 58.2475 26.1562C58.3398 25.8483 58.6203 25.6355 58.9419 25.6355H61.0918C61.5932 25.6355 62 25.2287 62 24.7272V20.1181C62 19.6167 61.5932 19.2099 61.0918 19.2099ZM54.1355 22.4227C54.1355 27.0101 50.4034 30.7427 45.816 30.7427C41.2282 30.7427 37.496 27.0105 37.496 22.4227C37.496 17.8348 41.2282 14.1027 45.816 14.1027C50.4034 14.1027 54.1355 17.8353 54.1355 22.4227V22.4227ZM24.513 22.4227C24.513 27.0153 20.7766 30.7512 16.184 30.7512C11.5919 30.7512 7.85548 27.0153 7.85548 22.4227C7.85548 17.8301 11.5919 14.0942 16.184 14.0942C20.7766 14.0942 24.513 17.8301 24.513 22.4227Z" fill="#EF5350"/>
            <path d="M61.0918 19.2099H58.9419C58.6203 19.2099 58.3398 18.9971 58.2475 18.6891C56.6227 13.2626 51.5855 9.44531 45.816 9.44531C39.9378 9.44531 34.8201 13.4078 33.2965 18.9975C31.7795 18.6617 30.2205 18.6617 28.7035 18.9975C27.1799 13.4078 22.0622 9.44531 16.184 9.44531C10.4145 9.44531 5.37732 13.2626 3.75249 18.6891C3.66025 18.9971 3.37975 19.2099 3.05809 19.2099H0.908203C0.406799 19.2099 0 19.6167 0 20.1181V24.7272C0 25.2291 0.406799 25.6355 0.908203 25.6355H3.05809C3.37975 25.6355 3.66072 25.8483 3.75249 26.1562C5.37732 31.5828 10.4145 35.4001 16.184 35.4001C21.3759 35.4001 26.0569 32.3178 28.1089 27.5479C28.6089 26.3861 29.7437 25.6355 31 25.6355C32.2563 25.6355 33.3911 26.3861 33.8911 27.5474C35.9431 32.3178 40.6241 35.4001 45.816 35.4001C51.5855 35.4001 56.6227 31.5828 58.2475 26.1562C58.3398 25.8483 58.6203 25.6355 58.9419 25.6355H61.0918C61.5932 25.6355 62 25.2287 62 24.7272V20.1181C62 19.6167 61.5932 19.2099 61.0918 19.2099ZM54.1355 22.4227C54.1355 27.0101 50.4034 30.7427 45.816 30.7427C41.2282 30.7427 37.496 27.0105 37.496 22.4227C37.496 17.8348 41.2282 14.1027 45.816 14.1027C50.4034 14.1027 54.1355 17.8353 54.1355 22.4227V22.4227ZM24.513 22.4227C24.513 27.0153 20.7766 30.7512 16.184 30.7512C11.5919 30.7512 7.85548 27.0153 7.85548 22.4227C7.85548 17.8301 11.5919 14.0942 16.184 14.0942C20.7766 14.0942 24.513 17.8301 24.513 22.4227Z" fill="white"/>
            </g>

        </svg>  
    </a>
<ul class="navbar-nav ml-auto mt-2 mt-lg-0" style="padding-right: 10px;">
    <li class="nav-item" >
    <a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" href="{% url 'homepage:tambah' %}">Inovasi Aktvitas</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" href="{% url 'story9:login' %}">Login</a>
    </li>
</ul>
</nav>

homepage/templates/tambah.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bootstrap-4.5.2-dist\css\bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="{% static 'bootstrap-4.5.2-dist\js\bootstrap.js' %}"></script>
    <title>tambah</title>
</head>
<body>
    {% include "navbar.html" %}
    <div class="container-fluid col-12 pt-5 m-auto">
        <section class="container-fluid flex-wrap align-content-center mb-5">
        <h1>
            Jelajahi Benak Rebahan
        </h1>
        <div class="pt-4">
            <form action="" method="post" novalidate>
                {% csrf_token %}
                <table class="table mx-5 table-borderless" style="width:60vw; color:white">
                    {{ form.as_table }}
                    {% if submit %}
                    <tr>
                    <td>&nbsp;</td>
                    <td>Successfully added an activity.</td>
                    </tr>
                    <tr>
                    <td>&nbsp;</td>
                    <td>
                        <button class="btn d-flex click" id="spesialbutton">
                        <a href="{% url 'homepage:tambah' %}" style="color:black">
                            Tambah Kembali
                        </a>
                        </button>
                    </td>
                    <td>
                        <button class="btn d-flex click" id="spesialbutton">
                        <a href="{% url 'homepage:index' %}" style="color:black">
                            Kembali
                        </a>
                        </button>
                    </td>
            
                    </tr>
                    {% else %}
                    <tr>
                    <td>&nbsp;</td>
                    <td>
                        <input type="submit" value="Submit" class="btn click" />
                    </td>
                    </tr>
                    {% endif %}
                </table>
                </form>
    
        </div>
        
        </section>
    </div>
</body>
</html>

story9/templates/index2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="{% static 'bootstrap-4.5.2-dist\css\bootstrap.css' %}">
    <script src="{% static 'bootstrap-4.5.2-dist\js\bootstrap.js' %}"></script>
    <title>Selamat Datang</title>
    <link rel="stylesheet" href="{% static 'style9.css' %}" />
</head>

<body>
    <div class="main">
        {% if user.is_authenticated %}
        <p> Hey, {{ user.username }}, looks like you've already signed in. Click <a
                href="{% url 'story9:login' %}">this link</a> to go back to homepage </p>
        {% else %}

        <h1>Buat Akun Baru</h1>

        <div class="container">
            <div class="row mt-4">
                <div class="col-lg-4 col-sm-2"></div>
                <form action="" method="POST" class="col-lg-4 col-sm-8 ">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="username" name="username" required>
                    </div>
                    <div class="form-group">
                        <input type="email" class="form-control" placeholder="e-mail" name="email" required>
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="password" name="password" required>
                    </div>
                    <button type="submit" class="btn btn-rose mt-3 mb-4" id="signup">daftar</button>
                </form>
                <div class="col-lg-4 col-sm-2"></div>
            </div>
        </div>

        <p>atau <a href="{% url 'story9:login' %}" style="font-weight: bold">log in</a> jika kamu sudah memiliki akun</p>

    </div>

    {% for message in messages %}
    <script>
        alert("{{ message }}")
    </script>
    {% endfor %}

    {% endif %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="{% static 'story10.js' %}"></script>
</body>

</html>

story9/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'bootstrap-4.5.2-dist\css\bootstrap.css' %}">
    <script src="{% static 'bootstrap-4.5.2-dist\js\bootstrap.js' %}"></script>
    <link rel="stylesheet" href="{% static 'style9.css' %}" />
</head>

<body>

    <div class="main">
        {% if user.is_authenticated %}
        <h1 style="font-size:80px"> Selamat {{ user.username }}! </h1>
        <p class="mt-5">Anda sekarang telah melihat bagaimana PPW akan segera berakhir :>
            <br>Semoga UAS nanti nilai Anda memuaskan!</p>

        <a href="{% url 'story9:logout' %}" class="btn btn-rose mt-5" id="logout" style="color: white;"
            name="logout">Log Out</a>

        {% else %}
        <h1>Selamat Datang</h1>
        <p>Masuk ke dalam akun mu!</p>
        <div class="container">
            <div class="row mt-4">
                <div class="col-lg-4 col-sm-2"></div>
                <form action="" method="POST" class="col-lg-4 col-sm-8 ">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="username" name="username" required>
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="password" name="password" required>
                    </div>
                    <button type="submit" class="btn btn-rose mt-3 mb-4" id="login">log in</button>
                </form>
                <div class="col-lg-4 col-sm-2"></div>
            </div>
        </div>

        <p>atau <a href="{% url 'story9:home' %}" style="font-weight: bold">sign up</a> jika kamu merasa belum memiliki akun</p>

        {% for message in messages %}
        <script>
            alert("{{ message }}")
        </script>
        {% endfor %}


        {% endif %}

    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

</body>

</html>